blog/urls.py
# main/blog/urls.py

# Django modules
from django.urls import path

# My modules
from . import views
from .feeds import LatestPostsFeed

# Define an application namespace
app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
] 

config/urls.py
# main/main/urls.py

# Django modules
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
# My modules
from blog import views


# Site maps
sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
# main/blog/models.py

# Django modules
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Third party modules
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    """
    Modifying our own manager
    """
    def get_query(self):
        return super(PublishedManager, 
                    self).get_queryset().filter(status='published')


class Post(models.Model):
    """
    It creates the post model
    """
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = RichTextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager() # Default manager
    published = PublishedManager() # Our custom manager

    
    class Meta:
        ordering = ('-publish',)
    
    # Canonical URLs form models
    # The convention in Django is to add a get_absolute_url()
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])
    

    def __str__(self):
        return self.title

    # It adds a tag
    tags = TaggableManager()

class Comment(models.Model):
    """
    Model to comment posts
    """
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    tags = TaggableManager()

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
# main/blog/forms.py

# Django modules
from django import forms

# My modules
from .models import Comment

class EmailPostForm(forms.Form):

    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    """
    Building a form dynamically from the model Comment
    """
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    """
    Allow users to search posts
    """
    query = forms.CharField()

blog/views.py
# main/blog/views.py

# Django modules
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

# Postgres modules
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank

# My modules
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm

def index(request):
    """
    Landing page
    """
    return render(request, 'index.html')

def post_list(request, tag_slug=None):
    """
    List posts views pagination
    """
    object_list = Post.published.all()
    tag = None
    
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
     
    return render(request,
                     'blog/post/list.html',
                    {'page': page, 
                    'posts': posts,
                    'tag': tag})


def post_detail(request, year, month, day, post):
    """
    Displaying a single post
    """
    post = get_object_or_404(Post, slug=post,
                            status='published',
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but do not save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

     # Lis of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request, 
                    'blog/post/detail.html', 
                    {'post': post,
                    'comments': comments,
                    'new_comment': new_comment,
                    'comment_form': comment_form,
                    'similar_posts': similar_posts})


def post_share(request, post_id):
    """
    Handle the form and send an email
    """
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    """
    Allow users to search posts
    """
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search = search_vector,
                rank = SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
            
    return render(request, 'blog/post/search.html',
                {'form': form,
                'query': query,
                'results': results})

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

   {% block content %}
        <h1>{{ post.title }}</h1>
        <p class="date">
        Publicado {{ post.publish }} por {{ post.author }}
        </p>
        {{ post.body|markdown }}

        <p>
            <a href="{% url 'blog:post_share' post.id %}">
                Comparte esta publicación
            </a>
        </p>

        <h2>Publicaciones Similares</h2>
        
        {% for post in similar_posts %}
            <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </p>
        {% empty %}
            No hay publicaciones similares.
        {% endfor %}
        
        {% with comments.count as total_comments  %}
            <h2>
                {{ total_comments }} comentario{{ total_comments|pluralize}}
            </h2>
        {% endwith %}
        
        {% comment %}
            Counting user comments
        {% endcomment %}
            
        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    Comentario {{ forloop.counter }} por {{ comment.name }}
                    {{ comment.created }}
                </p>
                {{ comment.body|linebreaks}}
            </div>
            {% empty %}
            <p>No hay comentarios, aún.</p>
        {% endfor %}
        
        {% comment %}
            Display comments or add a comment
        {% endcomment %}
                

        {% if new_comment %}
            <h2>Se agregó tu comentario.</h2>
        {% else %}
            <form action="." method="POST">
                {{ comment_form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
            </form>
        {% endif %}
            

    {% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    <!-- Display the last 5 posts by user -->
    {% for post in latest_post %}
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    {% endfor %}
        
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Jaso Salgado{% endblock %}

<p class="tags">
    Tags: 
    {% for tag in posts.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
</p> 

{% block content %}
    <h1>Perito Traductor & Desarrollador Backend</h1>
    {% if tag %}
        <h2>Publicaciones etiquetadas con "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>

        <p class="tags">
            Tags: 
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p> 

        <p class="date">
            Publicado {{ post.publish }} por {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}

    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}Buscar{% endblock title %}
    
{% block content %}
    
    {% if query %}
        <h1>Publicaciones que contienen "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
             {{ total_results }} resultados encontrado{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>No hay resultados para tu consulta.</p>
        {% endfor %}
            <p><a href="{% url 'blog:post_search' %}">Buscar nuevamente</a></p>
        {% else %}
            <h1>Buscar por publicación</h1>
            <form action="." method="get">
                {{ form.as_p }}
                <input type="submit" value="Buscar">
            </form>
    {% endif %}
        
{% endblock content %}
    

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}
    Comparte la publicación
{% endblock title %}

{% block content %}
    
    {% if sent %}
        <h1>Correo enviado exitosamente.</h1>
        <p>
            "{{ post.title }}" fue enviado exitosamente a {{ form.cleaned_data.to}}.
        </p>
    {% else %}
        <h1>Comparte "{{ post.title }}" por correo</h1>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Enviar correo">
        </form>
    {% endif %}
        
{% endblock content %}
    
    